# Generated by Django 4.2.1 on 2023-06-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='total_price',
        ),
    ]
