# Generated by Django 4.2.1 on 2023-05-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_categories_alter_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('Categories', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.FileField(blank=True, upload_to='photos/products')),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
    ]
