# Generated by Django 4.2.1 on 2023-05-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='Categories',
        ),
    ]
