# Generated by Django 4.2.1 on 2023-05-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_brand_categories_slug_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='price',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='stock',
        ),
    ]
