# Generated by Django 4.2.1 on 2023-06-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
