# Generated by Django 4.2.1 on 2023-06-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_colorvariation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='colorvariation',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
