# Generated by Django 4.2.1 on 2023-07-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariation',
            name='description',
            field=models.TextField(),
        ),
    ]
