# Generated by Django 4.2.1 on 2023-07-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_colorvariation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariation',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
