# Generated by Django 4.2.1 on 2023-07-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_colorvariation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariation',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount',
            field=models.BigIntegerField(null=True),
        ),
    ]
