# Generated by Django 4.2.1 on 2023-05-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adds',
            new_name='Ads',
        ),
        migrations.RenameField(
            model_name='ads',
            old_name='add_name',
            new_name='ad_name',
        ),
    ]
