# Generated by Django 4.2.1 on 2023-06-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='phone',
            field=models.IntegerField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
