# Generated by Django 4.2.1 on 2023-07-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_useraddress_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_otp',
            name='otp',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
