# Generated by Django 4.2.1 on 2023-06-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_colorvariation_image'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChartItem',
            new_name='CartItem',
        ),
    ]
